resources:
  - name: myBag_{{ .Values.name }}
    type: PropertyBag
    configuration:
      foo: bar

pipelines:
  - name: "two_step_{{ .Values.name }}"
    steps:
      - name: start
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start step"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent

      - name: end
        type: Bash
        configuration:
          inputSteps:
            - name: start
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "end step"
          onExecute:
            - printenv | grep parent

  - name: double_name_a
    steps:
      - name: double_name
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start step"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent
  - name: double_name_b
    steps:
      - name: double_name
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start step"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent

  - name: failer_{{ .Values.name }}
    steps:
      - name: start
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start the step, destined to fail"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent
            - badcmd


  - name: bad_pipes_{{ .Values.name }}
    steps:
      - name: self_cancel
        type: Bash
        execution:
          onExecute:
            - sleep 5
            - export payload="{\"statusCode\":\"4013\"}"
            - 'curl -XPUT -H "Authorization:Bearer $builder_api_token" -H "Content-type:application/json" $pipelines_api_url/steps/$step_id -d "$payload"'
            - sleep 60

      - name: self_error
        type: Bash
        configuration:
          inputSteps:
            - name: self_cancel
        execution:
          onExecute:
            - sleep 5
            - export payload="{\"statusCode\":\"4004\"}"
            - 'curl -XPUT -H "Authorization:Bearer $builder_api_token" -H "Content-type:application/json" $pipelines_api_url/steps/$step_id -d "$payload"'
            - 'curl -XPUT -H "Authorization:Bearer $builder_api_token" -H "Content-type:application/json" $pipelines_api_url/runs/$run_id -d "$payload"'
            - sleep 60