resources:
  - name: myBag_{{ .Values.name }}
    type: PropertyBag
    configuration:
      foo: bar

pipelines:
  - name: "two_step_{{ .Values.name }}"
    steps:
      - name: start
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start step"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent

      - name: end
        type: Bash
        configuration:
          inputSteps:
            - name: start
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "end step"
          onExecute:
            - printenv | grep parent

  - name: double_name_a
    steps:
      - name: double_name
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start step"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent
  - name: double_name_b
    steps:
      - name: double_name
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start step"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent

  - name: failer_{{ .Values.name }}
    steps:
      - name: start
        type: Bash
        configuration:
          inputResources:
            - name: myBag_{{ .Values.name }}
        execution:
          onStart:
            - echo "start the step, destined to fail"
          onExecute:
            - echo "foo is... $foo"
            - printenv | grep parent
            - badcmd